### ISSUE TITLE
Pytorch 1.4 support?

### ISSUE THREAD

**Issue by Ostyk** [laughtervv/DepthAwareCNN#36]
```
ostyk@pytorch:~/DepthAwareCNN/models/ops/depthconv$ sh make.sh 
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    from torch.utils.ffi import create_extension
  File "/home/ostyk/.local/lib/python3.5/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
```

Which torch version have you used? I'm not sure that fixing deprecated functions line by line is a very safe thing to do. Will be grateful for any tips. Thanks in advance.

**Comment by zeroXscorpion7** [comment]
pytorch 0.4.0
CUDA<=9.0

**Comment by lqzhao** [comment]
Hi, have you solved this problem, can you run depthconv using Pytorch 1.4 version? Thanks.

**Comment by Ostyk** [comment]
@lqzhao Hi, and no, not yet. I've put that project on pause. Once I continue it again, and I manage to make it work, I'll let you know here.

**Comment by DCC-lzhy** [comment]
> pytorch 0.4.0
> CUDA<=9.0

and which cudnn can be used? cudnn <=v7.0.5?

**Comment by Looottch** [comment]
> Hi, have you solved this problem, can you run depthconv using Pytorch 1.4 version? Thanks.



> Hi, have you solved this problem, can you run depthconv using Pytorch 1.4 version? Thanks.

Hi, I would like to ask have you solve this issue. Thanks in advance
