### ISSUE TITLE
how can i make lst file

### ISSUE THREAD

**Issue by fattyhu** [laughtervv/DepthAwareCNN#38]
I`m a student, now i run the code, when i run train.sh. I got some error:

Traceback (most recent call last):
  File "train.py", line 33, in <module>
    data_loader = CreateDataLoader(opt)
  File "/home/fattyhu/catkin_ws/DepthAwareCNN-master/data/data_loader.py", line 6, in CreateDataLoader
    data_loader.initialize(opt)
  File "/home/fattyhu/catkin_ws/DepthAwareCNN-master/data/custom_dataset_data_loader.py", line 51, in initialize
    self.dataset, self.dataset_val = CreateDataset(opt)
  File "/home/fattyhu/catkin_ws/DepthAwareCNN-master/data/custom_dataset_data_loader.py", line 40, in CreateDataset
    dataset.initialize(opt)
  File "/home/fattyhu/catkin_ws/DepthAwareCNN-master/data/nyuv2_dataset_crop.py", line 38, in initialize
    self.paths_dict = make_dataset_fromlst(opt.list)
  File "/home/fattyhu/catkin_ws/DepthAwareCNN-master/data/nyuv2_dataset_crop.py", line 23, in make_dataset_fromlst
    with open(listfilename) as f:
FileNotFoundError: [Errno 2] No such file or directory: './lists/train.lst'

how can i prepare the lst file?

**Comment by jinseok-karl** [comment]
https://github.com/laughtervv/DepthAwareCNN/issues/1#issuecomment-423048513 may help you

**Comment by fattyhu** [comment]
> [#1 (comment)](https://github.com/laughtervv/DepthAwareCNN/issues/1#issuecomment-423048513) may help you

Thanks for answer.
But before i ask, i already read that part. i`m a beginner, i run that code but failed. Maybe  somebody can tell me how to use the dataset and make the lst file.

**Comment by Peizhi86** [comment]
I am also a novice and cannot make this LST format dataset file now. I have been trying for half a month. I wonder if you have solved it, could you share it with me?
