### ISSUE TITLE
Use crmauceri's fork for a upto date version of this repo

### ISSUE THREAD

**Issue by njhofmann** [laughtervv/DepthAwareCNN#41]
User [crmauceri's rewriting of this repo](https://github.com/crmauceri/DepthAwareCNN-pytorch1.5) provides a more up-to date version of this paper's code that is compatible with the rewriting of PyTorch's extension interface with versions >1.0.0

**Comment by Andyshen555** [comment]
Have you been able to get the code from Crmauceri to run? I run into following error and cannot figure out how to solve:

running install
/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing depthconv.egg-info/PKG-INFO
writing dependency_links to depthconv.egg-info/dependency_links.txt
writing top-level names to depthconv.egg-info/top_level.txt
reading manifest file 'depthconv.egg-info/SOURCES.txt'
writing manifest file 'depthconv.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'depthconv' extension
Emitting ninja build file /home/shenyezh/DepthAwareCNN-pytorch1.5/depthaware/models/ops/depthconv/build/temp.linux-x86_64-3.8/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] /usr/local/cuda-10.2/bin/nvcc -I/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/include -I/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/include/TH -I/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/home/shenyezh/anaconda3/envs/depthcnn/include/python3.8 -c -c /home/shenyezh/DepthAwareCNN-pytorch1.5/depthaware/models/ops/depthconv/src/depthconv_cuda_kernel.cu -o /home/shenyezh/DepthAwareCNN-pytorch1.5/depthaware/models/ops/depthconv/build/temp.linux-x86_64-3.8/src/depthconv_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=depthconv -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
FAILED: /home/shenyezh/DepthAwareCNN-pytorch1.5/depthaware/models/ops/depthconv/build/temp.linux-x86_64-3.8/src/depthconv_cuda_kernel.o
/usr/local/cuda-10.2/bin/nvcc -I/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/include -I/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/include/TH -I/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-10.2/include -I/home/shenyezh/anaconda3/envs/depthcnn/include/python3.8 -c -c /home/shenyezh/DepthAwareCNN-pytorch1.5/depthaware/models/ops/depthconv/src/depthconv_cuda_kernel.cu -o /home/shenyezh/DepthAwareCNN-pytorch1.5/depthaware/models/ops/depthconv/build/temp.linux-x86_64-3.8/src/depthconv_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=depthconv -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/functional/padding.h(14): warning: integer conversion resulted in a change of sign

/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/functional/padding.h(15): warning: integer conversion resulted in a change of sign

/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/functional/padding.h(15): warning: integer conversion resulted in a change of sign

/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/functional/padding.h(15): warning: integer conversion resulted in a change of sign

/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/functional/padding.h(18): warning: integer conversion resulted in a change of sign

/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/functional/padding.h(19): warning: integer conversion resulted in a change of sign

/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/functional/padding.h(19): warning: integer conversion resulted in a change of sign

/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/functional/padding.h(19): warning: integer conversion resulted in a change of sign

/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/functional/padding.h(23): warning: integer conversion resulted in a change of sign

/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/functional/padding.h(24): warning: integer conversion resulted in a change of sign

/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/functional/padding.h(24): warning: integer conversion resulted in a change of sign

/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/nn/functional/padding.h(24): warning: integer conversion resulted in a change of sign

/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/profiler.h(100): warning: attribute "__visibility__" does not apply here

/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/profiler.h(115): warning: attribute "__visibility__" does not apply here

Segmentation fault (core dumped)
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1418, in _run_ninja_build
    subprocess.run(
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    setup(
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/_distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 603, in build_extensions
    build_ext.build_extensions(self)
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 428, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1158, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/shenyezh/anaconda3/envs/depthcnn/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1436, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
