### ISSUE TITLE
Cuda Illegal Memory Access

### ISSUE THREAD

**Issue by sabrinazuraimi** [laughtervv/DepthAwareCNN#8]
Sorry for always opening up issues here..
I tried looking around online, and I think the illegal memory access might have to do with the dataset that I'm using?(SUNRGBD dataset)
I can't think of any other reason for this error so would be much appreciated if you could help.

> CustomDatasetDataLoader
> dataset [sunrgbd_dataset] was created
> #training images = 5285
> model [BaseModel] was created
> create web directory ./checkpoints/test_depthconv/web...
> error in depthconv_col2im: an illegal memory access was encountered
> THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1513368888240/work/torch/lib/THC/generic/THCTensorMath.cu line=26 error=77 : an illegal memory access was encountered
> Traceback (most recent call last):
>   File "train.py", line 55, in <module>
>     model.backward(total_steps, opt.nepochs * dataset.__len__() * opt.batchSize + 1)
>   File "/disks/local/Documents/DepthAwareCNN-master/models/Deeplab.py", line 107, in backward
>     self.loss.backward()
>   File "/home/muser/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
>   File "/home/muser/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
>     variables, grad_variables, retain_graph)
>   File "/disks/local/Documents/DepthAwareCNN-master/models/ops/depthconv/functions/depthconv.py", line 91, in backward
>     grad_weight = weight.new(*weight.size()).zero_()
> RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1513368888240/work/torch/lib/THC/generic/THCTensorMath.cu:26
>

When I tried running it again today, the error no longer appeared(did not change anything with the code..)

**Comment by garrett-cn** [comment]
I have the same problem.Have you solved it?
